@Library('shared-library') _
pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                sh 'echo passed'
           }
        }

        stage('Build Docker'){
            steps{
                dockerImage("prajj29/cicd-e2e:${BUILD_NUMBER}")
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    pushImage("prajj29/cicd-e2e:${BUILD_NUMBER}")
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git url: 'https://github.com/prajwalrai25/Jenkins-Zero-To-Hero',
                    branch: 'main'
            
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            environment {
                GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
                GIT_USER_NAME = "prajwalrai25"
            }
            steps {
                script{
                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')])  {
                        sh '''
                        git config user.name "prajwalrai25"
                        git config user.email "your-email@gmail.com"
                        cd python-jenkins-argocd-k8s/deploy
                        cat deploy.yaml
                        sed -i "s|image: prajj29/cicd-e2e:.*|image: prajj29/cicd-e2e:${BUILD_NUMBER}|g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://${GIT_USER_NAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
